version: '3.8'

services:
  auth:
    build: ./auth-service
    ports:
      - "5000:5000"
    networks:
      - app_network

  data-entry:
    build: ./data-entry-service
    ports:
      - "5001:5001"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - app_network

  analytics:
    build: ./analytics-service
    ports:
      - "5002:5002"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - app_network

  show-results:
    build: ./show-results-service
    ports:
      - "5003:5003"
    depends_on:
      - mongo
    networks:
      - app_network

  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: data_db
    ports:
      - "3308:3306"
    networks:
      - app_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s

  mongo:
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    networks:
      - app_network


networks:
  app_network:
